### ISSUE TITLE
Vuex 4 support

### ISSUE THREAD

**Issue by reecehill** [brophdawg11/vuex-helpers#22]
Hi,

This package would be amazing if it supported Vuex4. 

Are there any plans to do so?

Many thanks

**Comment by reecehill** [comment]
Sorry! I just went ahead and installed it anyway:
`npm install --save @urbn/vuex-helpers --legacy-peer-deps`

It seems to be working. No compilation errors and output is as expected.

**Comment by brophdawg11** [comment]
I would probably recommend forking copies of these utilities into your local app if you are using it - this was extracted a long time ago but we never actually started using this package and I've since left that position so this package is not looked at or maintained anymore.  Glad to hear it's working for you!
